// ignore_for_file: camel_case_types, non_constant_identifier_names,
//                  unnecessary_brace_in_string_interps, unused_element,
//                  always_specify_types

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Auto-generated FFI bindings for libmusicchain C API.
class MusicChainBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MusicChainBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  MusicChainBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  late final ffi.Pointer<ffi.UintPtr> ___security_cookie =
      _lookup<ffi.UintPtr>('__security_cookie');

  int get __security_cookie => ___security_cookie.value;

  set __security_cookie(int value) => ___security_cookie.value = value;

  /// Initialize the library. Call once before any other function.
  /// Returns 0 on success, non-zero on failure.
  int mc_init() {
    return _mc_init();
  }

  late final _mc_initPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('mc_init');
  late final _mc_init = _mc_initPtr.asFunction<int Function()>();

  /// Release all library resources.
  void mc_cleanup() {
    return _mc_cleanup();
  }

  late final _mc_cleanupPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('mc_cleanup');
  late final _mc_cleanup = _mc_cleanupPtr.asFunction<void Function()>();

  /// Free a string or buffer allocated by the library.
  void mc_free(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _mc_free(
      ptr,
    );
  }

  late final _mc_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'mc_free');
  late final _mc_free =
      _mc_freePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  /// Returns the last error message as a null-terminated string, or NULL.
  ffi.Pointer<ffi.Char> mc_last_error() {
    return _mc_last_error();
  }

  late final _mc_last_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'mc_last_error');
  late final _mc_last_error =
      _mc_last_errorPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Load an existing wallet from path.
  /// Returns a wallet handle, or NULL on failure.
  mc_wallet_t mc_wallet_load(
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _mc_wallet_load(
      path,
      password,
    );
  }

  late final _mc_wallet_loadPtr = _lookup<
      ffi.NativeFunction<
          mc_wallet_t Function(
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('mc_wallet_load');
  late final _mc_wallet_load = _mc_wallet_loadPtr.asFunction<
      mc_wallet_t Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// Save wallet to path. Returns 0 on success.
  int mc_wallet_save(
    mc_wallet_t wallet,
    ffi.Pointer<ffi.Char> path,
  ) {
    return _mc_wallet_save(
      wallet,
      path,
    );
  }

  late final _mc_wallet_savePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              mc_wallet_t, ffi.Pointer<ffi.Char>)>>('mc_wallet_save');
  late final _mc_wallet_save = _mc_wallet_savePtr
      .asFunction<int Function(mc_wallet_t, ffi.Pointer<ffi.Char>)>();

  /// Release wallet handle.
  void mc_wallet_free(
    mc_wallet_t wallet,
  ) {
    return _mc_wallet_free(
      wallet,
    );
  }

  late final _mc_wallet_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(mc_wallet_t)>>(
          'mc_wallet_free');
  late final _mc_wallet_free =
      _mc_wallet_freePtr.asFunction<void Function(mc_wallet_t)>();

  /// Get wallet address as a 40-character hex string (20 bytes).
  /// Caller must free with mc_free().
  ffi.Pointer<ffi.Char> mc_wallet_get_address(
    mc_wallet_t wallet,
  ) {
    return _mc_wallet_get_address(
      wallet,
    );
  }

  late final _mc_wallet_get_addressPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(mc_wallet_t)>>(
          'mc_wallet_get_address');
  late final _mc_wallet_get_address = _mc_wallet_get_addressPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(mc_wallet_t)>();

  /// Get compressed public key as a 66-character hex string (33 bytes).
  /// Caller must free with mc_free().
  ffi.Pointer<ffi.Char> mc_wallet_get_public_key(
    mc_wallet_t wallet,
  ) {
    return _mc_wallet_get_public_key(
      wallet,
    );
  }

  late final _mc_wallet_get_public_keyPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(mc_wallet_t)>>(
          'mc_wallet_get_public_key');
  late final _mc_wallet_get_public_key = _mc_wallet_get_public_keyPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(mc_wallet_t)>();

  /// Sign data with the wallet private key.
  /// Returns 128-character hex string (64-byte signature), or NULL on failure.
  /// Caller must free with mc_free().
  ffi.Pointer<ffi.Char> mc_wallet_sign(
    mc_wallet_t wallet,
    ffi.Pointer<ffi.Uint8> data,
    int len,
  ) {
    return _mc_wallet_sign(
      wallet,
      data,
      len,
    );
  }

  late final _mc_wallet_signPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(mc_wallet_t, ffi.Pointer<ffi.Uint8>,
              ffi.Size)>>('mc_wallet_sign');
  late final _mc_wallet_sign = _mc_wallet_signPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          mc_wallet_t, ffi.Pointer<ffi.Uint8>, int)>();

  /// Open an Ogg/Vorbis or Ogg/Opus decoder from raw data.
  /// Returns a decoder handle, or NULL on failure.
  mc_decoder_t mc_decoder_open(
    ffi.Pointer<ffi.Uint8> data,
    int len,
  ) {
    return _mc_decoder_open(
      data,
      len,
    );
  }

  late final _mc_decoder_openPtr = _lookup<
      ffi.NativeFunction<
          mc_decoder_t Function(
              ffi.Pointer<ffi.Uint8>, ffi.Size)>>('mc_decoder_open');
  late final _mc_decoder_open = _mc_decoder_openPtr
      .asFunction<mc_decoder_t Function(ffi.Pointer<ffi.Uint8>, int)>();

  /// Release decoder handle.
  void mc_decoder_free(
    mc_decoder_t decoder,
  ) {
    return _mc_decoder_free(
      decoder,
    );
  }

  late final _mc_decoder_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(mc_decoder_t)>>(
          'mc_decoder_free');
  late final _mc_decoder_free =
      _mc_decoder_freePtr.asFunction<void Function(mc_decoder_t)>();

  /// Get sample rate in Hz.
  int mc_decoder_get_sample_rate(
    mc_decoder_t decoder,
  ) {
    return _mc_decoder_get_sample_rate(
      decoder,
    );
  }

  late final _mc_decoder_get_sample_ratePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(mc_decoder_t)>>(
          'mc_decoder_get_sample_rate');
  late final _mc_decoder_get_sample_rate =
      _mc_decoder_get_sample_ratePtr.asFunction<int Function(mc_decoder_t)>();

  /// Get channel count.
  int mc_decoder_get_channels(
    mc_decoder_t decoder,
  ) {
    return _mc_decoder_get_channels(
      decoder,
    );
  }

  late final _mc_decoder_get_channelsPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(mc_decoder_t)>>(
          'mc_decoder_get_channels');
  late final _mc_decoder_get_channels =
      _mc_decoder_get_channelsPtr.asFunction<int Function(mc_decoder_t)>();

  /// Get total duration in milliseconds.
  int mc_decoder_get_duration_ms(
    mc_decoder_t decoder,
  ) {
    return _mc_decoder_get_duration_ms(
      decoder,
    );
  }

  late final _mc_decoder_get_duration_msPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function(mc_decoder_t)>>(
          'mc_decoder_get_duration_ms');
  late final _mc_decoder_get_duration_ms =
      _mc_decoder_get_duration_msPtr.asFunction<int Function(mc_decoder_t)>();

  /// Decode up to max_samples interleaved signed-16-bit samples into buf.
  /// Returns number of samples decoded, 0 at EOF, -1 on error.
  int mc_decoder_read(
    mc_decoder_t decoder,
    ffi.Pointer<ffi.Int16> buf,
    int max_samples,
  ) {
    return _mc_decoder_read(
      decoder,
      buf,
      max_samples,
    );
  }

  late final _mc_decoder_readPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(mc_decoder_t, ffi.Pointer<ffi.Int16>,
              ffi.Int)>>('mc_decoder_read');
  late final _mc_decoder_read = _mc_decoder_readPtr
      .asFunction<int Function(mc_decoder_t, ffi.Pointer<ffi.Int16>, int)>();

  /// Seek to position in milliseconds. Returns 0 on success.
  int mc_decoder_seek(
    mc_decoder_t decoder,
    int position_ms,
  ) {
    return _mc_decoder_seek(
      decoder,
      position_ms,
    );
  }

  late final _mc_decoder_seekPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(mc_decoder_t, ffi.Uint32)>>(
          'mc_decoder_seek');
  late final _mc_decoder_seek =
      _mc_decoder_seekPtr.asFunction<int Function(mc_decoder_t, int)>();

  /// Get current playback position in milliseconds.
  int mc_decoder_position_ms(
    mc_decoder_t decoder,
  ) {
    return _mc_decoder_position_ms(
      decoder,
    );
  }

  late final _mc_decoder_position_msPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function(mc_decoder_t)>>(
          'mc_decoder_position_ms');
  late final _mc_decoder_position_ms =
      _mc_decoder_position_msPtr.asFunction<int Function(mc_decoder_t)>();

  /// Compute heartbeat checksum over interleaved signed-16-bit samples.
  /// sum = sum of abs(sample) for all samples, result = sum mod 2^32.
  int mc_compute_checksum(
    ffi.Pointer<ffi.Int16> samples,
    int count,
  ) {
    return _mc_compute_checksum(
      samples,
      count,
    );
  }

  late final _mc_compute_checksumPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(
              ffi.Pointer<ffi.Int16>, ffi.Int)>>('mc_compute_checksum');
  late final _mc_compute_checksum = _mc_compute_checksumPtr
      .asFunction<int Function(ffi.Pointer<ffi.Int16>, int)>();

  /// Generate a Chromaprint fingerprint from raw Ogg data.
  /// Returns a fingerprint handle, or NULL on failure.
  mc_fingerprint_t mc_fingerprint_generate(
    ffi.Pointer<ffi.Uint8> data,
    int len,
  ) {
    return _mc_fingerprint_generate(
      data,
      len,
    );
  }

  late final _mc_fingerprint_generatePtr = _lookup<
      ffi.NativeFunction<
          mc_fingerprint_t Function(
              ffi.Pointer<ffi.Uint8>, ffi.Size)>>('mc_fingerprint_generate');
  late final _mc_fingerprint_generate = _mc_fingerprint_generatePtr
      .asFunction<mc_fingerprint_t Function(ffi.Pointer<ffi.Uint8>, int)>();

  /// Load fingerprint from base64-compressed string.
  /// Returns a fingerprint handle, or NULL on failure.
  mc_fingerprint_t mc_fingerprint_from_compressed(
    ffi.Pointer<ffi.Char> base64,
  ) {
    return _mc_fingerprint_from_compressed(
      base64,
    );
  }

  late final _mc_fingerprint_from_compressedPtr = _lookup<
          ffi.NativeFunction<mc_fingerprint_t Function(ffi.Pointer<ffi.Char>)>>(
      'mc_fingerprint_from_compressed');
  late final _mc_fingerprint_from_compressed =
      _mc_fingerprint_from_compressedPtr
          .asFunction<mc_fingerprint_t Function(ffi.Pointer<ffi.Char>)>();

  /// Release fingerprint handle.
  void mc_fingerprint_free(
    mc_fingerprint_t fp,
  ) {
    return _mc_fingerprint_free(
      fp,
    );
  }

  late final _mc_fingerprint_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(mc_fingerprint_t)>>(
          'mc_fingerprint_free');
  late final _mc_fingerprint_free =
      _mc_fingerprint_freePtr.asFunction<void Function(mc_fingerprint_t)>();

  /// Get compressed base64 fingerprint string.
  /// Caller must free with mc_free().
  ffi.Pointer<ffi.Char> mc_fingerprint_get_compressed(
    mc_fingerprint_t fp,
  ) {
    return _mc_fingerprint_get_compressed(
      fp,
    );
  }

  late final _mc_fingerprint_get_compressedPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(mc_fingerprint_t)>>(
      'mc_fingerprint_get_compressed');
  late final _mc_fingerprint_get_compressed = _mc_fingerprint_get_compressedPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(mc_fingerprint_t)>();

  /// Compare two fingerprints; returns similarity in [0.0, 1.0].
  double mc_fingerprint_compare(
    mc_fingerprint_t fp_a,
    mc_fingerprint_t fp_b,
  ) {
    return _mc_fingerprint_compare(
      fp_a,
      fp_b,
    );
  }

  late final _mc_fingerprint_comparePtr = _lookup<
      ffi.NativeFunction<
          ffi.Float Function(
              mc_fingerprint_t, mc_fingerprint_t)>>('mc_fingerprint_compare');
  late final _mc_fingerprint_compare = _mc_fingerprint_comparePtr
      .asFunction<double Function(mc_fingerprint_t, mc_fingerprint_t)>();

  /// Find separator (8 x 0xFF bytes) in block data.
  /// Returns byte offset of separator start, or -1 if not found.
  int mc_block_find_separator(
    ffi.Pointer<ffi.Uint8> data,
    int len,
  ) {
    return _mc_block_find_separator(
      data,
      len,
    );
  }

  late final _mc_block_find_separatorPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(
              ffi.Pointer<ffi.Uint8>, ffi.Size)>>('mc_block_find_separator');
  late final _mc_block_find_separator = _mc_block_find_separatorPtr
      .asFunction<int Function(ffi.Pointer<ffi.Uint8>, int)>();

  /// Extract Ogg audio data from a serialized block.
  /// Allocates *ogg_out; caller must free with mc_free().
  /// Returns 0 on success.
  int mc_block_extract_audio(
    ffi.Pointer<ffi.Uint8> block_data,
    int block_len,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> ogg_out,
    ffi.Pointer<ffi.Size> ogg_len_out,
  ) {
    return _mc_block_extract_audio(
      block_data,
      block_len,
      ogg_out,
      ogg_len_out,
    );
  }

  late final _mc_block_extract_audioPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Uint8>,
              ffi.Size,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
              ffi.Pointer<ffi.Size>)>>('mc_block_extract_audio');
  late final _mc_block_extract_audio = _mc_block_extract_audioPtr.asFunction<
      int Function(ffi.Pointer<ffi.Uint8>, int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>, ffi.Pointer<ffi.Size>)>();

  /// Compute SHA-256 of data and write 32 bytes to out_hash.
  void mc_sha256(
    ffi.Pointer<ffi.Uint8> data,
    int len,
    ffi.Pointer<ffi.Uint8> out_hash,
  ) {
    return _mc_sha256(
      data,
      len,
      out_hash,
    );
  }

  late final _mc_sha256Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Size,
              ffi.Pointer<ffi.Uint8>)>>('mc_sha256');
  late final _mc_sha256 = _mc_sha256Ptr.asFunction<
      void Function(ffi.Pointer<ffi.Uint8>, int, ffi.Pointer<ffi.Uint8>)>();

  /// Convert bytes to hex string. Caller must free with mc_free().
  ffi.Pointer<ffi.Char> mc_bytes_to_hex(
    ffi.Pointer<ffi.Uint8> data,
    int len,
  ) {
    return _mc_bytes_to_hex(
      data,
      len,
    );
  }

  late final _mc_bytes_to_hexPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<ffi.Uint8>, ffi.Size)>>('mc_bytes_to_hex');
  late final _mc_bytes_to_hex = _mc_bytes_to_hexPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Uint8>, int)>();

  /// Convert hex string to bytes.
  /// Allocates *out; caller must free with mc_free().
  /// Returns number of bytes, or -1 on error.
  int mc_hex_to_bytes(
    ffi.Pointer<ffi.Char> hex,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _mc_hex_to_bytes(
      hex,
      out,
    );
  }

  late final _mc_hex_to_bytesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>)>>('mc_hex_to_bytes');
  late final _mc_hex_to_bytes = _mc_hex_to_bytesPtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Uint8>>)>();
}

final class __crt_locale_data_public extends ffi.Struct {
  external ffi.Pointer<ffi.UnsignedShort> _locale_pctype;

  @ffi.Int()
  external int _locale_mb_cur_max;

  @ffi.UnsignedInt()
  external int _locale_lc_codepage;
}

final class __crt_locale_pointers extends ffi.Struct {
  external ffi.Pointer<__crt_locale_data> locinfo;

  external ffi.Pointer<__crt_multibyte_data> mbcinfo;
}

final class __crt_locale_data extends ffi.Opaque {}

final class __crt_multibyte_data extends ffi.Opaque {}

final class _Mbstatet extends ffi.Struct {
  @ffi.UnsignedLong()
  external int _Wchar;

  @ffi.UnsignedShort()
  external int _Byte;

  @ffi.UnsignedShort()
  external int _State;
}

typedef mc_wallet_t = ffi.Pointer<ffi.Void>;
typedef mc_decoder_t = ffi.Pointer<ffi.Void>;
typedef mc_fingerprint_t = ffi.Pointer<ffi.Void>;

const int _VCRT_COMPILER_PREPROCESSOR = 1;

const int _SAL_VERSION = 20;

const int __SAL_H_VERSION = 180000000;

const int _USE_DECLSPECS_FOR_SAL = 0;

const int _USE_ATTRIBUTES_FOR_SAL = 0;

const int _CRT_PACKING = 8;

const int _VCRUNTIME_DISABLED_WARNINGS = 4514;

const int _HAS_EXCEPTIONS = 1;

const int _WCHAR_T_DEFINED = 1;

const int NULL = 0;

const int _HAS_CXX17 = 0;

const int _HAS_CXX20 = 0;

const int _HAS_CXX23 = 0;

const int _HAS_CXX26 = 0;

const int _HAS_NODISCARD = 1;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -2147483648;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 2147483647;

const int INT_FAST32_MAX = 2147483647;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = 4294967295;

const int UINT_FAST32_MAX = 4294967295;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIZE_MAX = -1;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int WCHAR_MIN = 0;

const int WCHAR_MAX = 65535;

const int WINT_MIN = 0;

const int WINT_MAX = 65535;

const int _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE = 1;

const int _CRT_BUILD_DESKTOP_APP = 1;

const int _UCRT_DISABLED_WARNINGS = 4324;

const int _ARGMAX = 100;

const int _TRUNCATE = -1;

const int _CRT_INT_MAX = 2147483647;

const int _CRT_SIZE_MAX = -1;

const String __FILEW__ = 'C';

const int _CRT_FUNCTIONS_REQUIRED = 1;

const int _CRT_HAS_CXX17 = 0;

const int _CRT_HAS_C11 = 0;

const int _CRT_INTERNAL_NONSTDC_NAMES = 1;

const int __STDC_SECURE_LIB__ = 200411;

const int __GOT_SECURE_LIB__ = 200411;

const int __STDC_WANT_SECURE_LIB__ = 1;

const int _SECURECRT_FILL_BUFFER_PATTERN = 254;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES = 0;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT = 0;

const int _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES = 1;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY = 0;

const int _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY = 0;

const int _STATIC_INLINE_UCRT_FUNCTIONS = 1;

const int MC_FORMAT_UNKNOWN = 0;

const int MC_FORMAT_OGG = 1;

const int MC_FORMAT_MP3 = 2;
